listat_homepage:
    path:     /
    defaults: { _controller: ListatBundle:User:user }

listat_project_list:
    path:     /project/{id}
    defaults: { _controller: ListatBundle:Project:projectList }

listat_delete_project:
    path:   /project/delete/{id}
    defaults: { _controller: ListatBundle:Project:delete }

listat_edit_project:
    path:   /project/edit/{id}
    defaults: { _controller: ListatBundle:Project:edit }

listat_task_list:
    path:   /task/{id}
    defaults: { _controller: ListatBundle:Task:taskList }

listat_delete_task:
    path:   /task/delete/{id}
    defaults: { _controller: ListatBundle:Task:delete }

listat_edit_task:
    path:   /task/edit/{id}
    defaults: { _controller: ListatBundle:Task:edit }