listat_homepage:
    path:     /
    defaults: { _controller: ListatBundle:Project:index }

listat_tasklist:
    path:   /project/{id}
    defaults: { _controller: ListatBundle:Task:tasklist }

listat_delete_project:
    path:   /project/delete/{id}
    defaults: { _controller: ListatBundle:Project:delete }

listat_edit_project:
    path:   /project/edit/{id}
    defaults: { _controller: ListatBundle:Project:edit }

listat_delete_task:
    path:   /task/delete/{id}
    defaults: { _controller: ListatBundle:Task:delete }

listat_edit_task:
    path:   /task/edit/{id}
    defaults: { _controller: ListatBundle:Task:edit }